spring.datasource.url=jdbc:mysql://localhost:3306/dogsdb
spring.datasource.username=root
spring.datasource.password=Sayan@321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9090